#!/usr/bin/env bash
# This script displays numbers from 1 to 20 with bad luck messages for 4, 9, and 17
i=1
while [ $i -le 20 ]; do
    case $i in
        4) echo "4 and then bad luck from China" ;;
        9) echo "9 and then bad luck from Japan" ;;
        17) echo "17 and then bad luck from Italy" ;;
        *) echo "$i" ;;
    esac
    ((i++))
done
